### ISSUE TITLE
Root access still allowed until reboot

### ISSUE THREAD

**Issue by bitwombat** [nickjj/ansible-sshd#3]
Interestingly, on a Digital Ocean "drop" (Ubuntu 16.04), sshd was still allowing root login after this role/task was run.  Confirmed /etc/ssh/sshd_config had "PermitRootLogin no".  

This was even after doing a `systemctl restart ssh.service`

After a reboot, root was no longer permitted.

Not sure how to debug this further.

**Comment by nickjj** [comment]
That is really interesting, thanks for the report. Did you isolate it to 16.x specifically?

I will look into this today and get back to you.

Restarting the ssh service should be enough for the changes to come into effect.

**Comment by nickjj** [comment]
Follow up question: What happens if you create the droplet with an SSH key attached to it?

**Comment by bitwombat** [comment]
Found it.  I have my client ssh's config set to persist connections (ControlPersist), so there's an sshd child process sitting there on the destination, waiting for a reconnect, and persisting past the restart.

So... not really an issue, since nobody outside my system would be able to still log in as root (confirmed this).

**Comment by nickjj** [comment]
Thanks for the report. That makes sense.
