### ISSUE TITLE
"Shutting the door" to root and subsequent playbook runs

### ISSUE THREAD

**Issue by bitwombat** [nickjj/ansible-sshd#4]
In a new Digital Ocean instance, root access with a public key is set up.

So, my playbook has:

````
remote_user: root
````

However, with ansible-user, I set up an 'app' user, then ansible-sshd here closes the door to root access.

That means subsequent runs of my playbook can't get in unless I edit the playbook to:

````
remote_user: app
become: true
````

That's not ideal.  Essentially, the remote system has a state that fact-gathering can't really test or do anything about.

My options:

1) Two playbooks.  One sets up the new user 'app' (as root), then shuts the door on root.  The other playbook uses the new user and 'becomes'.  Person needs to know to run first playbook once only.  Human-based state knowledge = boo hiss

2)  Manually creating user 'app' and always using 'app' as the remote_user.  Manual = boo hiss

Something better??

**Comment by nickjj** [comment]
Thanks for the report.

I think option 1 is out of the question because like you said, having to run 2 playbooks will induce snake noises.

In my playbooks I typically run my user role before ssh, this way that user ends up being configured to connect via SSH before the lockout happens. Then at the playbook level I set `become: True` and things work. No need to set `remote_user`.

But, I am going to leave this open because I've encountered lock outs before but it's something I was never able to reproduce 100% of the time.

**Comment by bitwombat** [comment]
I had a third icky idea - each IP is part of two host groups.  Maybe "brand_new_droplets" and "droplets".    Then I'm either running a playbook against an inventory of brand new machines, or repeatedly against some that have already had their initial setup done.

Then I'm using host_vars or something to set the remote_user.

>In my playbooks I typically run my user role before ssh, this way that user ends up being configured to 
>connect via SSH before the lockout happens. Then at the playbook level I set become: True

I don't see how that works... with `become: True` and no `remote_user` ansible tries to ssh without a user@...

And with that little experiment, I just proved fail2ban is doing its job!

**Comment by bitwombat** [comment]
I've tried a few more things (two plays in the playbook) and nothing works right - no matter what, the play that relies on being able to get in as 'root' won't work once the door is shut.

One of ansible's cool features is its "idempotency", but with this I have to edit the playbook depending on whether or not its been run before.

It's almost like the fact gathering needs to check if the root user is allowed, and if not, set user/become options appropriately.  I mean, it *is* state, after all, that's changed on the machine.

**Comment by nickjj** [comment]
After thinking about this for a while and consulting with Ansible master @drybjed I don't think there's a reasonable way around it without introducing dynamic inventories.

I think you're stuck setting `ssh_user` in your inventory file after the first run. You shouldn't have to touch your playbook, which is a plus.

If that's unacceptable, you can write a task to hack around this by setting the ssh_user value for you locally but I feel like that might be best suited towards a custom role / task outside the scope of this role. Willing to hear a counter argument on this topic tho. If it were to be implemented, it would definitely need to be opt-in.

**Comment by bitwombat** [comment]
Thanks for thinking about it some more and for the new ideas.  It's *got* to be a common problem, right?

The only other way I've thought of is moving hosts from a group called "Brand new" to whatever they were going to be called from the first run onwards.

**Comment by nickjj** [comment]
Yeah it's definitely common. Your idea would work too. Sounds like you should test both solutions and see which one works best out in the wild.

**Comment by bitwombat** [comment]
Here's what I settled on, though I'm suspecting the 'right way is adding some sort of complicated custom fact that discovers if root has been disabled.

So I have a first_time.yml playbook and a app_server.yml playbook.  It's up to me to remember run the first_time once.

Done.

Seems non-ideal but at some point its time to the reign in the OCD yak shaving and just get on with it :)

Thanks for the dialog.

**Comment by bitwombat** [comment]
One more thing.  You didn't answer how this could work on subsequent runs:

> In my playbooks I typically run my user role before ssh, this way that user ends up being configured to 
>connect via SSH before the lockout happens. Then at the playbook level I set become: True and things 
>work. No need to set remote_user.

For the user role to run the first time, it would need ssh_user = root, but next time, ssh_user = user.  

With no remote_user set, ansible tries to ssh as root by default.

**Comment by nickjj** [comment]
Right, before the second run you would need to edit your inventory. Something like:

```
[foo]
192.168.1.2 ansible_user="deploy"
```

Without the ansible_user, like you said it would use "root", but onwards from here it would use "deploy".

That pattern is described here: http://docs.ansible.com/ansible/intro_inventory.html#list-of-behavioral-inventory-parameters

**Comment by bitwombat** [comment]
Hi Nick,

Here's the best I came up with... for future Googlers, and for me when I forget I even asked this in 6 months and come across my own thread here with a Google search.

1. Set a new variable 'initial_user' in group_vars, on a per-group (per-provider) basis, eg.

````
[aws]
initial_user: ubuntu

[digital-ocean]
initial_user: root
````

2. Set become: true and become_user: root in all plays in all playbooks.  This is the cool thing - if the ansible_ssh_user is root, this has no effect.  That greatly simplifies things.  

3. Use ansible-sshd as per normal.

A play that sets up a standard non-root user looks like this:

````
- hosts: all

  remote_user: '{{ initial_user }}'
  become: true
  become_user: root

  roles:
    - ansible-user
    - ansible-sshd
````

Other plays then do:

````
- hosts: all

  remote_user: my_standard_username
  become: true
  become_user: root
````

So now no editing of inventory files, group_vars, or playbooks is req'd after the first run.
